id: P000270
initial_creation_type: ebook
source_metadata:
  title: ༄༅། །དྲི་མེད་སྣང་བ་གྲུབ་པ་མཆོག་གི་ཞལ་ལུང་ཞེས་བྱ་བ། གྲུབ་ཐོབ་དམ་པ་སངས་རྒྱས་ནས་བརྒྱུད་པའི་དམ་ཆོས་སྡུག་བསྔལ་ཞི་བྱེད་ཀྱི་ལམ་ལྔའི་ཁྲིད་ཡིག་བཞུགས་སོ།
    །
  authors:
  - མཛད་པ་པོ་དངོས། སྙེ་མདོ་བསོད་ནམས་དཔལ།
  layers:
  - book_title
  - author
  - chapter_title
  - yigchung
  id: LS-ZHI-05-11
web_metadata:
  title:
    en: The Words of Stainless Vision and the Supreme Siddha:The Instructions on the
      Five Paths of Padampa Sangye on the Pacification of Suffering
    bo: དྲི་མེད་སྣང་བ་གྲུབ་པ་མཆོག་གི་ཞལ་ལུང་ཞེས་བྱ་བ། གྲུབ་ཐོབ་དམ་པ་སངས་རྒྱས་ནས་བརྒྱུད་པའི་དམ་ཆོས་སྡུག་བསྔལ་ཞི་བྱེད་ཀྱི་ལམ་ལྔའི་ཁྲིད་ཡིག་བཞུགས་སོ།
  collection:
    en: Zhije Series–  Book 5-11
    bo: ཞི་བྱེད།–  དེབ། ༥-༡༡
  author:
    en: Tsele Natsok Rangdrol
    bo: རྩེ་ལེ་སྣ་ཚོགས་རང་གྲོལ།
  pusblisher:
    en: Dingri Langkor Zhijed Ling
    bo: དིང་རི་གླང་སྐོར་ཞི་བྱེད་གླིང་།
  sku: LS-ZHI-05-11
  category:
    en: ''
    bo: ''
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: LS-ZHI-05-11.epub
  description:
    en: ''
    bo: ''
